"""add due_date and make fields optional in paper table

Revision ID: 12d3e1eea61e
Revises: 92591674d0a3
Create Date: 2025-08-24 22:45:12.887087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12d3e1eea61e'
down_revision: Union[str, Sequence[str], None] = '92591674d0a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('grade',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('path',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('memo',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper', schema=None) as batch_op:
        batch_op.alter_column('memo',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('path',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('grade',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('subject',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('due_date')

    # ### end Alembic commands ###
