"""Modify Paper table

Revision ID: 6ac25b44bb63
Revises: 
Create Date: 2025-08-20 15:46:43.973235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6ac25b44bb63'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sqlmodel.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('paper', sqlmodel.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('paper', sqlmodel.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('paper', 'memo',
               existing_type=sqlmodel.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paper', 'memo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('paper', 'status')
    op.drop_column('paper', 'type')
    op.drop_column('paper', 'author')
    # ### end Alembic commands ###
