"""add review fields to paper table

Revision ID: 92591674d0a3
Revises: 6ac25b44bb63
Create Date: 2025-08-24 22:18:49.717670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92591674d0a3'
down_revision: Union[str, Sequence[str], None] = '6ac25b44bb63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('review_stage', sa.Integer(), nullable=True))
    op.add_column('paper', sa.Column('next_review_date', sa.DateTime(), nullable=True))
    op.add_column('paper', sa.Column('last_reviewed_at', sa.DateTime(), nullable=True))
    op.alter_column('paper', 'memo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('paper', 'memo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('paper', 'last_reviewed_at')
    op.drop_column('paper', 'next_review_date')
    op.drop_column('paper', 'review_stage')
    # ### end Alembic commands ###
