"""add description to paper table

Revision ID: bd60f3fb02aa
Revises: 12d3e1eea61e
Create Date: 2025-08-24 23:14:56.627192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd60f3fb02aa'
down_revision: Union[str, Sequence[str], None] = '12d3e1eea61e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
